### ISSUE TITLE
command 'mavensmate.newProject' not found

### ISSUE THREAD

**Issue by ivan-tadic-cloudsense** [joeferraro/MavensMate-VisualStudioCode#5]
After adding extension to the ~/.vscode/extensions folder and running npm install, I can see new commands available. However, I get following message when trying to create new MavensMate project:

`command 'mavensmate.newProject' not found`

Same issue happens for other commands too.

**Comment by joeferraro** [comment]
Appreciate the enthusiasm but this isn't GA yet :) will launch at
Dreamforce.

**Comment by ivan-tadic-cloudsense** [comment]
:) My bad then. Thanks for the reply. I'm excited to see this working.

**Comment by kidtsunami** [comment]
Haha @ivan-tadic-cloudsense stay excited, we're thankful you're looking forward to this.
